### ISSUE TITLE
Custom date range?

### ISSUE THREAD

**Issue by genetsen** [jdharrisnz/datorama-d3-quick-trends#1]
How do you set up this custom date range within Datorama?  is it in the JS code, do I create it custom dimensions for start/end, or is it set within the date range filter in-widget?  In the last case, i can not find a way to add code to the in-widget filter.

Thank you for the code and in advance for the clarification!

_Date Range
The widget will not do any normalisation for part-filled date ranges, but it will add a warning for incomplete first or last periods. Therefore, it's recommended to use 'previous' settings wherever possible. For example, the image **uses a custom date range** for 'Previous 4 Weeks'. Here's how that's set up: ..._

**Comment by jdharrisnz** [comment]
Hey genetsen, thanks for asking. Custom date ranges are in the workspace settings. Here's a help link: https://help.salesforce.com/s/articleView?id=sf.dato_getstarted_custom_date_range_create.htm&type=5
